Server code refactoring and minor docs updates
epicweb-dev/epic-stack pull request #668
Opened 2024-03-24 15:58 UTC by rustworthy

## Test Plan

- Removed duplicated globals patching in dev more;
- sentry/remix can now handle `getBuild` [correctly](https://github.com/getsentry/sentry-javascript/compare/7.105.0...7.107.0#diff-73298ca0f16878e3602c16356e48fdd7d13fc660510f2475300138185eb0d712R58-R86)
- Updated docs on monitoring.

## Checklist

- [ ] Tests updated N/A
- [x] Docs updated

## Screenshots

2024-03-24 16:00 UTC, rustworthy commented on server/index.ts
> -		desiredPort === portToUse
A tine [chance](https://github.com/sindresorhus/get-port?tab=readme-ov-file#beware), but still it makes sense to only trust the OS's final decision ;)

2024-03-25 22:12 UTC, kentcdodds requested changes
Thanks! Just a few suggestions.

2024-03-25 22:12 UTC, kentcdodds commented on server/index.ts
> +		// https://github.com/helmetjs/helmet?tab=readme-ov-file#x-powered-by
We don't need to include links for every single thing here. People can look it up if they want.

```suggestion
```

2024-03-25 22:12 UTC, kentcdodds commented on server/index.ts
> +const portToUser = await getPort({
Looks like a typo?

```suggestion
const portToUse = await getPort({
```

2024-03-25 22:12 UTC, kentcdodds commented on server/index.ts
> +const server = app.listen(portToUser, () => {
Typo?
```suggestion
const server = app.listen(portToUse, () => {
```

2024-03-26 02:54 UTC, rustworthy commented on server/index.ts
> +const portToUser = await getPort({
It is

2024-03-26 03:36 UTC, kentcdodds approved these changes
Thanks!

2024-03-26 03:36 UTC, merged