add control over indexability
epicweb-dev/epic-stack pull request #679
Opened 2024-03-30 01:00 UTC by nichtsam

We don't over duplicate content from different environment to all be indexed by search engines, \
this PR adds control over indexability.

For seo safety reason, I decided it's better to allow indexing by default.

`<meta name="robots" content="noindex, nofollow" />` prevents HTML from being indexed.
`X-Robots-Tag` prevents all resource from being indexed, this is mainly for non-HTML resources, such as PDF files, video files, or image files.

## Test Plan

I don't see a test that brings much confidence here.

## Checklist

- [ ] Tests updated
- [ ] Docs updated

## Screenshots

2024-03-30 21:24 UTC, kentcdodds requested changes
Thanks! This looks pretty good. Just a simple suggestion.

2024-03-30 21:24 UTC, kentcdodds commented on app/root.tsx
> +				{disallowIndexing && <meta name="robots" content="noindex, nofollow" />}
```suggestion
				{allowIndexing ? null : <meta name="robots" content="noindex, nofollow" />}
```

2024-03-30 21:24 UTC, kentcdodds commented on .env.example
> +DISALLOW_INDEXING="false"
I generally prefer variables not use negation. So this should instead be "ALLOW_INDEXING" which defaults to `true`

2024-03-30 21:24 UTC, kentcdodds commented on app/root.tsx
> +	disallowIndexing,
This should be:

```suggestion
	allowIndexing = true,
```

2024-03-30 23:45 UTC, nichtsam commented
I use `process.env.ALLOW_INDEXING !== 'false'` to get the boolean, so only explicitly setting it to false will disallow the indexing.
And I realized `.default()` isn't really safe in this case, because it would declare type as `"true" | "false"` while it's actually `"true" | "false" | undefined`, and since it's default to true, it's important to be aware of the `undefined` case.

2024-04-01 16:54 UTC, kentcdodds approved these changes
Super. Thank you!

2024-04-01 16:54 UTC, merged