fix: ignore generated icons folder
epicweb-dev/epic-stack pull request #729
Opened 2024-05-10 18:46 UTC by isaacplmann

When an app is created with create-epic-app, the gitignore file does not include /app/components/ui/icons

## Test Plan

1. `npx create-epic-app`
2. Look at the `.gitignore` file

2024-05-10 20:00 UTC, kentcdodds requested changes
This is already included: https://github.com/epicweb-dev/epic-stack/blob/69b42889b894ff952f9267931801adc1dfb46cdc/.gitignore#L25

🤔

2024-05-11 01:32 UTC, isaacplmann commented
Maybe this file is not the correct place to make the change, but when you run `npx create-epic-app` the `.gitignore` file does not have the `/app/components/ui/icons` line.

2024-05-11 05:27 UTC, jacobparis commented
Maybe we should just remove it from the .remix-init entirely if it's overwriting the real one

2024-05-14 02:59 UTC, kentcdodds approved these changes
Oops, that's right. Thanks!

2024-05-14 02:59 UTC, merged